// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthHistory is the predicate function for authhistory builders.
type AuthHistory func(*sql.Selector)

// Passkey is the predicate function for passkey builders.
type Passkey func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
