// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Minto312/passkey-practice/backend/ent/passkey"
	"github.com/Minto312/passkey-practice/backend/ent/predicate"
	"github.com/Minto312/passkey-practice/backend/ent/user"
	"github.com/google/uuid"
)

// PasskeyUpdate is the builder for updating Passkey entities.
type PasskeyUpdate struct {
	config
	hooks    []Hook
	mutation *PasskeyMutation
}

// Where appends a list predicates to the PasskeyUpdate builder.
func (pu *PasskeyUpdate) Where(ps ...predicate.Passkey) *PasskeyUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetCredentialID sets the "credential_id" field.
func (pu *PasskeyUpdate) SetCredentialID(s string) *PasskeyUpdate {
	pu.mutation.SetCredentialID(s)
	return pu
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (pu *PasskeyUpdate) SetNillableCredentialID(s *string) *PasskeyUpdate {
	if s != nil {
		pu.SetCredentialID(*s)
	}
	return pu
}

// SetPublicKey sets the "public_key" field.
func (pu *PasskeyUpdate) SetPublicKey(b []byte) *PasskeyUpdate {
	pu.mutation.SetPublicKey(b)
	return pu
}

// SetDeviceName sets the "device_name" field.
func (pu *PasskeyUpdate) SetDeviceName(s string) *PasskeyUpdate {
	pu.mutation.SetDeviceName(s)
	return pu
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (pu *PasskeyUpdate) SetNillableDeviceName(s *string) *PasskeyUpdate {
	if s != nil {
		pu.SetDeviceName(*s)
	}
	return pu
}

// SetLastUsedAt sets the "last_used_at" field.
func (pu *PasskeyUpdate) SetLastUsedAt(t time.Time) *PasskeyUpdate {
	pu.mutation.SetLastUsedAt(t)
	return pu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (pu *PasskeyUpdate) SetUserID(id uuid.UUID) *PasskeyUpdate {
	pu.mutation.SetUserID(id)
	return pu
}

// SetUser sets the "user" edge to the User entity.
func (pu *PasskeyUpdate) SetUser(u *User) *PasskeyUpdate {
	return pu.SetUserID(u.ID)
}

// Mutation returns the PasskeyMutation object of the builder.
func (pu *PasskeyUpdate) Mutation() *PasskeyMutation {
	return pu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (pu *PasskeyUpdate) ClearUser() *PasskeyUpdate {
	pu.mutation.ClearUser()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PasskeyUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PasskeyUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PasskeyUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PasskeyUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *PasskeyUpdate) defaults() {
	if _, ok := pu.mutation.LastUsedAt(); !ok {
		v := passkey.UpdateDefaultLastUsedAt()
		pu.mutation.SetLastUsedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PasskeyUpdate) check() error {
	if pu.mutation.UserCleared() && len(pu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Passkey.user"`)
	}
	return nil
}

func (pu *PasskeyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(passkey.Table, passkey.Columns, sqlgraph.NewFieldSpec(passkey.FieldID, field.TypeUUID))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.CredentialID(); ok {
		_spec.SetField(passkey.FieldCredentialID, field.TypeString, value)
	}
	if value, ok := pu.mutation.PublicKey(); ok {
		_spec.SetField(passkey.FieldPublicKey, field.TypeBytes, value)
	}
	if value, ok := pu.mutation.DeviceName(); ok {
		_spec.SetField(passkey.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := pu.mutation.LastUsedAt(); ok {
		_spec.SetField(passkey.FieldLastUsedAt, field.TypeTime, value)
	}
	if pu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkey.UserTable,
			Columns: []string{passkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkey.UserTable,
			Columns: []string{passkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PasskeyUpdateOne is the builder for updating a single Passkey entity.
type PasskeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PasskeyMutation
}

// SetCredentialID sets the "credential_id" field.
func (puo *PasskeyUpdateOne) SetCredentialID(s string) *PasskeyUpdateOne {
	puo.mutation.SetCredentialID(s)
	return puo
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (puo *PasskeyUpdateOne) SetNillableCredentialID(s *string) *PasskeyUpdateOne {
	if s != nil {
		puo.SetCredentialID(*s)
	}
	return puo
}

// SetPublicKey sets the "public_key" field.
func (puo *PasskeyUpdateOne) SetPublicKey(b []byte) *PasskeyUpdateOne {
	puo.mutation.SetPublicKey(b)
	return puo
}

// SetDeviceName sets the "device_name" field.
func (puo *PasskeyUpdateOne) SetDeviceName(s string) *PasskeyUpdateOne {
	puo.mutation.SetDeviceName(s)
	return puo
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (puo *PasskeyUpdateOne) SetNillableDeviceName(s *string) *PasskeyUpdateOne {
	if s != nil {
		puo.SetDeviceName(*s)
	}
	return puo
}

// SetLastUsedAt sets the "last_used_at" field.
func (puo *PasskeyUpdateOne) SetLastUsedAt(t time.Time) *PasskeyUpdateOne {
	puo.mutation.SetLastUsedAt(t)
	return puo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (puo *PasskeyUpdateOne) SetUserID(id uuid.UUID) *PasskeyUpdateOne {
	puo.mutation.SetUserID(id)
	return puo
}

// SetUser sets the "user" edge to the User entity.
func (puo *PasskeyUpdateOne) SetUser(u *User) *PasskeyUpdateOne {
	return puo.SetUserID(u.ID)
}

// Mutation returns the PasskeyMutation object of the builder.
func (puo *PasskeyUpdateOne) Mutation() *PasskeyMutation {
	return puo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (puo *PasskeyUpdateOne) ClearUser() *PasskeyUpdateOne {
	puo.mutation.ClearUser()
	return puo
}

// Where appends a list predicates to the PasskeyUpdate builder.
func (puo *PasskeyUpdateOne) Where(ps ...predicate.Passkey) *PasskeyUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PasskeyUpdateOne) Select(field string, fields ...string) *PasskeyUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Passkey entity.
func (puo *PasskeyUpdateOne) Save(ctx context.Context) (*Passkey, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PasskeyUpdateOne) SaveX(ctx context.Context) *Passkey {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PasskeyUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PasskeyUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *PasskeyUpdateOne) defaults() {
	if _, ok := puo.mutation.LastUsedAt(); !ok {
		v := passkey.UpdateDefaultLastUsedAt()
		puo.mutation.SetLastUsedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PasskeyUpdateOne) check() error {
	if puo.mutation.UserCleared() && len(puo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Passkey.user"`)
	}
	return nil
}

func (puo *PasskeyUpdateOne) sqlSave(ctx context.Context) (_node *Passkey, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passkey.Table, passkey.Columns, sqlgraph.NewFieldSpec(passkey.FieldID, field.TypeUUID))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Passkey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, passkey.FieldID)
		for _, f := range fields {
			if !passkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != passkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.CredentialID(); ok {
		_spec.SetField(passkey.FieldCredentialID, field.TypeString, value)
	}
	if value, ok := puo.mutation.PublicKey(); ok {
		_spec.SetField(passkey.FieldPublicKey, field.TypeBytes, value)
	}
	if value, ok := puo.mutation.DeviceName(); ok {
		_spec.SetField(passkey.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := puo.mutation.LastUsedAt(); ok {
		_spec.SetField(passkey.FieldLastUsedAt, field.TypeTime, value)
	}
	if puo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkey.UserTable,
			Columns: []string{passkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkey.UserTable,
			Columns: []string{passkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Passkey{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
