// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Minto312/passkey-practice/backend/ent/passkey"
	"github.com/Minto312/passkey-practice/backend/ent/user"
	"github.com/google/uuid"
)

// PasskeyCreate is the builder for creating a Passkey entity.
type PasskeyCreate struct {
	config
	mutation *PasskeyMutation
	hooks    []Hook
}

// SetCredentialID sets the "credential_id" field.
func (pc *PasskeyCreate) SetCredentialID(s string) *PasskeyCreate {
	pc.mutation.SetCredentialID(s)
	return pc
}

// SetPublicKey sets the "public_key" field.
func (pc *PasskeyCreate) SetPublicKey(s string) *PasskeyCreate {
	pc.mutation.SetPublicKey(s)
	return pc
}

// SetDeviceName sets the "device_name" field.
func (pc *PasskeyCreate) SetDeviceName(s string) *PasskeyCreate {
	pc.mutation.SetDeviceName(s)
	return pc
}

// SetCreatedAt sets the "created_at" field.
func (pc *PasskeyCreate) SetCreatedAt(t time.Time) *PasskeyCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PasskeyCreate) SetNillableCreatedAt(t *time.Time) *PasskeyCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetLastUsedAt sets the "last_used_at" field.
func (pc *PasskeyCreate) SetLastUsedAt(t time.Time) *PasskeyCreate {
	pc.mutation.SetLastUsedAt(t)
	return pc
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (pc *PasskeyCreate) SetNillableLastUsedAt(t *time.Time) *PasskeyCreate {
	if t != nil {
		pc.SetLastUsedAt(*t)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *PasskeyCreate) SetID(u uuid.UUID) *PasskeyCreate {
	pc.mutation.SetID(u)
	return pc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pc *PasskeyCreate) SetNillableID(u *uuid.UUID) *PasskeyCreate {
	if u != nil {
		pc.SetID(*u)
	}
	return pc
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (pc *PasskeyCreate) AddUserIDs(ids ...uuid.UUID) *PasskeyCreate {
	pc.mutation.AddUserIDs(ids...)
	return pc
}

// AddUser adds the "user" edges to the User entity.
func (pc *PasskeyCreate) AddUser(u ...*User) *PasskeyCreate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return pc.AddUserIDs(ids...)
}

// Mutation returns the PasskeyMutation object of the builder.
func (pc *PasskeyCreate) Mutation() *PasskeyMutation {
	return pc.mutation
}

// Save creates the Passkey in the database.
func (pc *PasskeyCreate) Save(ctx context.Context) (*Passkey, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PasskeyCreate) SaveX(ctx context.Context) *Passkey {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PasskeyCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PasskeyCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PasskeyCreate) defaults() {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := passkey.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.LastUsedAt(); !ok {
		v := passkey.DefaultLastUsedAt()
		pc.mutation.SetLastUsedAt(v)
	}
	if _, ok := pc.mutation.ID(); !ok {
		v := passkey.DefaultID()
		pc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PasskeyCreate) check() error {
	if _, ok := pc.mutation.CredentialID(); !ok {
		return &ValidationError{Name: "credential_id", err: errors.New(`ent: missing required field "Passkey.credential_id"`)}
	}
	if _, ok := pc.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`ent: missing required field "Passkey.public_key"`)}
	}
	if _, ok := pc.mutation.DeviceName(); !ok {
		return &ValidationError{Name: "device_name", err: errors.New(`ent: missing required field "Passkey.device_name"`)}
	}
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Passkey.created_at"`)}
	}
	if _, ok := pc.mutation.LastUsedAt(); !ok {
		return &ValidationError{Name: "last_used_at", err: errors.New(`ent: missing required field "Passkey.last_used_at"`)}
	}
	return nil
}

func (pc *PasskeyCreate) sqlSave(ctx context.Context) (*Passkey, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PasskeyCreate) createSpec() (*Passkey, *sqlgraph.CreateSpec) {
	var (
		_node = &Passkey{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(passkey.Table, sqlgraph.NewFieldSpec(passkey.FieldID, field.TypeUUID))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pc.mutation.CredentialID(); ok {
		_spec.SetField(passkey.FieldCredentialID, field.TypeString, value)
		_node.CredentialID = value
	}
	if value, ok := pc.mutation.PublicKey(); ok {
		_spec.SetField(passkey.FieldPublicKey, field.TypeString, value)
		_node.PublicKey = value
	}
	if value, ok := pc.mutation.DeviceName(); ok {
		_spec.SetField(passkey.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.SetField(passkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.LastUsedAt(); ok {
		_spec.SetField(passkey.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = value
	}
	if nodes := pc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   passkey.UserTable,
			Columns: passkey.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PasskeyCreateBulk is the builder for creating many Passkey entities in bulk.
type PasskeyCreateBulk struct {
	config
	err      error
	builders []*PasskeyCreate
}

// Save creates the Passkey entities in the database.
func (pcb *PasskeyCreateBulk) Save(ctx context.Context) ([]*Passkey, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Passkey, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PasskeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PasskeyCreateBulk) SaveX(ctx context.Context) []*Passkey {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PasskeyCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PasskeyCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
